-- ============================================================================
-- Migration: Initial Schema for 10xCards
-- Created: 2025-11-12
-- Description: Creates the core database schema for the flashcard application
--
-- Tables affected:
--   - generations: Stores AI-generated flashcard batch metadata
--   - flashcards: Main table for user flashcards with FSRS algorithm support
--   - generation_error_logs: Logs errors during AI generation process
--
-- Features:
--   - Row Level Security (RLS) enabled on all tables
--   - Automatic updated_at timestamps via triggers
--   - Indexes for query optimization
--   - Cascading deletes for data integrity
--
-- Notes:
--   - users table is managed by Supabase Auth (auth.users)
--   - All user_id references point to auth.users(id)
--   - FSRS algorithm columns: due, stability, difficulty, last_reviewed_at
-- ============================================================================

-- ============================================================================
-- SECTION 1: Helper Functions
-- ============================================================================

-- Function to automatically update the updated_at column
-- This function will be used by triggers to maintain accurate modification timestamps
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ============================================================================
-- SECTION 2: Create Tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table: generations
-- Purpose: Stores metadata about AI-generated flashcard batches
-- Dependencies: auth.users (Supabase Auth)
-- Relationships: One-to-many with flashcards (optional reference)
-- ----------------------------------------------------------------------------
create table generations (
  -- Primary key: BIGSERIAL for auto-incrementing ID
  id bigserial primary key,

  -- Foreign key to Supabase Auth users
  -- ON DELETE CASCADE: When user is deleted, all their generations are deleted
  user_id uuid not null references auth.users(id) on delete cascade,

  -- AI model used for generation (e.g., 'gpt-4', 'claude-3')
  model varchar not null,

  -- Number of flashcards generated in this batch
  generated_count integer not null,

  -- Number of flashcards accepted without editing
  -- NULL until user reviews the generation
  accepted_unedited_count integer,

  -- Number of flashcards accepted after editing
  -- NULL until user reviews the generation
  accepted_edited_count integer,

  -- Hash of source text to detect duplicates and track what was used
  source_text_hash varchar not null,

  -- Length of source text in characters
  -- Constrained to 1000-10000 characters for quality control
  source_text_length integer not null check (source_text_length between 1000 and 10000),

  -- Time taken to generate flashcards in milliseconds
  generation_duration integer not null,

  -- Timestamp when generation was created
  created_at timestamptz not null default now(),

  -- Timestamp when generation was last modified
  -- Automatically updated by trigger
  updated_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- Table: flashcards
-- Purpose: Main table storing user flashcards with spaced repetition data
-- Dependencies: auth.users, generations (optional)
-- Relationships: Many-to-one with users, many-to-one with generations (optional)
-- FSRS Algorithm: Uses due, stability, difficulty, last_reviewed_at columns
-- ----------------------------------------------------------------------------
create table flashcards (
  -- Primary key: BIGSERIAL for auto-incrementing ID
  id bigserial primary key,

  -- Foreign key to Supabase Auth users
  -- ON DELETE CASCADE: When user is deleted, all their flashcards are deleted
  user_id uuid not null references auth.users(id) on delete cascade,

  -- Optional reference to the generation that created this flashcard
  -- ON DELETE SET NULL: If generation is deleted, flashcard remains but loses reference
  -- This allows manual flashcards (generation_id = NULL) and preserves AI-generated cards
  generation_id bigint references generations(id) on delete set null,

  -- Front side of flashcard (question/prompt)
  -- Max 200 characters, must not be empty
  front varchar(200) not null check (length(front) > 0),

  -- Back side of flashcard (answer/explanation)
  -- Max 500 characters, must not be empty
  back varchar(500) not null check (length(back) > 0),

  -- Source of the flashcard:
  --   'manual': Created manually by user
  --   'ai-full': Generated by AI, not edited by user
  --   'ai-edited': Generated by AI, then edited by user
  -- Application should change 'ai-full' to 'ai-edited' on first edit
  source varchar(20) not null default 'manual' check (source in ('ai-full', 'ai-edited', 'manual')),

  -- FSRS Algorithm: When the card is due for review
  -- Default NOW() makes new cards immediately available for study
  due timestamptz not null default now(),

  -- FSRS Algorithm: Memory stability (how well the card is remembered)
  -- Higher values = longer intervals between reviews
  -- Default 0 for new cards
  stability real not null default 0,

  -- FSRS Algorithm: Card difficulty (how hard it is to remember)
  -- Higher values = card is more difficult
  -- Default 0 for new cards
  difficulty real not null default 0,

  -- FSRS Algorithm: Timestamp of last review
  -- NULL for cards that haven't been reviewed yet
  last_reviewed_at timestamptz,

  -- Timestamp when flashcard was created
  created_at timestamptz not null default now(),

  -- Timestamp when flashcard was last modified
  -- Automatically updated by trigger
  updated_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- Table: generation_error_logs
-- Purpose: Logs errors that occur during AI flashcard generation
-- Dependencies: auth.users
-- Relationships: Many-to-one with users
-- ----------------------------------------------------------------------------
create table generation_error_logs (
  -- Primary key: BIGSERIAL for auto-incrementing ID
  id bigserial primary key,

  -- Foreign key to Supabase Auth users
  -- ON DELETE CASCADE: When user is deleted, all their error logs are deleted
  user_id uuid not null references auth.users(id) on delete cascade,

  -- AI model that was being used when error occurred
  model varchar not null,

  -- Hash of source text that caused the error (for debugging)
  source_text_hash varchar not null,

  -- Length of source text that caused the error
  -- Same constraints as generations table for consistency
  source_text_length integer not null check (source_text_length between 1000 and 10000),

  -- Error code for categorization (e.g., 'RATE_LIMIT', 'INVALID_RESPONSE')
  error_code varchar(100) not null,

  -- Detailed error message for debugging
  error_message text not null,

  -- Timestamp when error occurred
  created_at timestamptz not null default now()
);

-- ============================================================================
-- SECTION 3: Create Indexes
-- ============================================================================

-- Index for quickly fetching all generations for a specific user
-- Used in: User dashboard, generation history
create index idx_generations_user_id on generations(user_id);

-- Index for quickly fetching all flashcards for a specific user
-- Used in: Flashcard list, study session initialization
create index idx_flashcards_user_id on flashcards(user_id);

-- Index for quickly fetching flashcards from a specific generation
-- Used in: Generation review, acceptance workflow
create index idx_flashcards_generation_id on flashcards(generation_id);

-- Index for efficiently querying flashcards due for review
-- Used in: Study session, finding next cards to review
-- Critical for FSRS algorithm performance
create index idx_flashcards_due on flashcards(due);

-- Index for quickly fetching error logs for a specific user
-- Used in: Admin dashboard, user support, error analysis
create index idx_generation_error_logs_user_id on generation_error_logs(user_id);

-- ============================================================================
-- SECTION 4: Create Triggers
-- ============================================================================

-- Trigger to automatically update updated_at in generations table
-- Fires before any UPDATE operation on the generations table
create trigger update_generations_updated_at
  before update on generations
  for each row
  execute function update_updated_at_column();

-- Trigger to automatically update updated_at in flashcards table
-- Fires before any UPDATE operation on the flashcards table
create trigger update_flashcards_updated_at
  before update on flashcards
  for each row
  execute function update_updated_at_column();

-- ============================================================================
-- SECTION 5: Enable Row Level Security
-- ============================================================================

-- Enable RLS on all tables to ensure data access is properly controlled
-- Even if policies allow public access, RLS must be enabled
alter table generations enable row level security;
alter table flashcards enable row level security;
alter table generation_error_logs enable row level security;

-- ============================================================================
-- SECTION 6: Create RLS Policies - generations table
-- ============================================================================

-- Policy: Allow authenticated users to view their own generations
-- Rationale: Users should only see generations they created
-- Scope: SELECT operations for authenticated users
create policy "authenticated_users_select_own_generations"
  on generations
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Policy: Allow authenticated users to insert their own generations
-- Rationale: Users can create new generations for themselves
-- Scope: INSERT operations for authenticated users
create policy "authenticated_users_insert_own_generations"
  on generations
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to update their own generations
-- Rationale: Users can modify metadata of their generations (e.g., acceptance counts)
-- Scope: UPDATE operations for authenticated users
create policy "authenticated_users_update_own_generations"
  on generations
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to delete their own generations
-- Rationale: Users can remove generation records they no longer need
-- Note: This won't delete associated flashcards (ON DELETE SET NULL)
-- Scope: DELETE operations for authenticated users
create policy "authenticated_users_delete_own_generations"
  on generations
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- ============================================================================
-- SECTION 7: Create RLS Policies - flashcards table
-- ============================================================================

-- Policy: Allow authenticated users to view their own flashcards
-- Rationale: Users should only see flashcards they own
-- Scope: SELECT operations for authenticated users
create policy "authenticated_users_select_own_flashcards"
  on flashcards
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Policy: Allow authenticated users to insert their own flashcards
-- Rationale: Users can create new flashcards for themselves
-- Scope: INSERT operations for authenticated users
create policy "authenticated_users_insert_own_flashcards"
  on flashcards
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to update their own flashcards
-- Rationale: Users can edit flashcard content and update FSRS algorithm data
-- Scope: UPDATE operations for authenticated users
create policy "authenticated_users_update_own_flashcards"
  on flashcards
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to delete their own flashcards
-- Rationale: Users can remove flashcards they no longer want to study
-- Scope: DELETE operations for authenticated users
create policy "authenticated_users_delete_own_flashcards"
  on flashcards
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- ============================================================================
-- SECTION 8: Create RLS Policies - generation_error_logs table
-- ============================================================================

-- Policy: Allow authenticated users to view their own error logs
-- Rationale: Users can see errors that occurred during their generation attempts
-- Scope: SELECT operations for authenticated users
create policy "authenticated_users_select_own_error_logs"
  on generation_error_logs
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Policy: Allow authenticated users to insert their own error logs
-- Rationale: Application can log errors on behalf of the user
-- Scope: INSERT operations for authenticated users
create policy "authenticated_users_insert_own_error_logs"
  on generation_error_logs
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Note: No UPDATE or DELETE policies for error logs
-- Error logs are immutable records for auditing and debugging purposes
-- Only administrators should be able to modify or delete error logs (via direct DB access)

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================

